---
  - name: Update repos (was not working from apt:)
    command: sudo apt-get update -y
  - name: Install Prereqs [SLOW]
    apt: name={{ item }} state=latest
    with_items:
      - git
      - screen
      - qemu-kvm
      - libvirt-bin
      - ubuntu-vm-builder
      - bridge-utils
      - ruby1.9.1-dev
      - make
      - curl
  - name: gem install kvm slaves
    command: sudo gem install json net-http-digest_auth
    args:
      creates: /var/lib/gems/1.9.1/cache/json-1.8.3.gem
  - name: stop apparmor
    command: sudo service apparmor teardown
  - name: remove apparmor
    command: sudo update-rc.d -f apparmor remove

